language: shell
sudo: true
addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - jq
            - linkchecker
install:
    - mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ~/bin
script:
    - reviewdog -conf=./.reviewdog.yml -reporter=github-pr-check
    - shellcheck -x tests/spellchecker/spell_checker.sh
    - bash tests/spellchecker/spell_checker.sh
