language: shell
sudo: true
addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - jq
            - linkchecker
script:
    - shellcheck -x tests/spellchecker/spell_checker.sh
    - bash tests/spellchecker/spell_checker.sh
    - reviewdog -reporter=github-prcheck
