language: shell
sudo: true
addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - jq
            - linkchecker
script:
#    - bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'
    - bash script.sh
