language: shell
sudo: true
addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - jq
            - linkchecker
script:
    - shellcheck main.sh
    - bash main.sh
